version: '3.6'

services:
    postgres:
        image: postgres:10
        container_name: some-postgres
        environment:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: hellokoding
          POSTGRES_DB: kafka-sink
        command: docker-entrypoint.sh -c unix_socket_directories=/var/run/postgresql,/tmp
        #> /var/lib/postgresql/data/postgresql.conf"
        ports:
          - 5432:5432